### PR TITLE
Add Support for Setting Azure Location for Testing and Upload Pester Test Output Artefacts - Fixes #19 #20

### LINKED ISSUE #19: Use Push-AppveyorArtifact to upload test results to AppVeyor
Is it possible to use the `Push-AppVeyorArtifact` cmdlet (available in AppVeyor) to publish the results of testing artifacts instead of the WebClient with a URL specified in the `AppVeyor.yml`?

This would slightly simplify the code and eliminate the need for the `TestResultsUploadURI` in the AppVeyor.yml file in each DSC Configuration repo.

The only reason to keep this as WebClient upload would be to allow uploading from outside AppVeyor or to another destination, but I don't know if this was a requirement.

I can submit a PR with this change if acceptable.

### LINKED ISSUE #20: Add ability to change Azure resource deployment location
Some Azure subscriptions don't allow VM's in some locations depending on the tier.

For example:
https://ci.appveyor.com/project/PlagueHO/dockerenterprisedscconfig/build/1.0.6.0#L186

Therefore it would be good to be able to allow overriding of the Azure Resource Group location by specifying an $env: parameter which could be set via AppVeyor.yml.

I can submit a PR for this as well.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR addresses:
 - Fixes #19 
 - Fixes #20 

The main issue I ran into when creating a config using this pattern was that my Azure subscription for some reason didn't allow me to create the VMs required to execute the automated tests in the default EastUS2 data center. So I needed a way to override the location.

I also find it useful to upload the Pester test results into AppVeyor as files I can download and distribute (as we do with DSC Resource Kit).

As I was also making changes to this, I thought a Changelog should also be included in the README.MD so I added one.

This PR changes:
* README.MD:
  * Fixed markdown rule violations.
  * Added Change Log.
* Added support for specifying the Azure Data center location to use
  by defining the `$ENV:Location` environment variable. Will default
  to 'EastUS2' if not specified.
* NUnit Pester Test results uploaded to AppVeyor as artifacts.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscconfiguration.tests/21)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Tagging @zjalexander and @mgreenegit as per DSC community call instruction.

**Comment by johlju** [comment]
I have made a bunch of fixes that I can send in, but I need this one to merge first, because I'm dependent on this one.
Commits that are pending to be sent in; https://github.com/johlju/DscConfiguration.Tests/commits/fixes-issues

**Comment by johlju** [comment]
This PR is pointing to merged into master, shouldn't it be merged into dev first? See issue #30.

**Comment by mgreenegit** [comment]
Looks good.  Thank you!

**Pull request merged**
